name: Ping Render Server Every 10 Minutes

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Service
        run: curl https://membership-management-system.onrender.com/